baseURL = 'http://localhost:1313'
title = 'Notes with AI'
languageCode = 'en-us'
defaultContentLanguage = 'en'
hasCJKLanguage = true
enableGitInfo = true
enableInlineShortcodes = true

[module]
[[module.imports]]
  path = 'github.com/imfing/hextra'

[caches]
[caches.images]
dir = ':cacheDir/images'

[languages]
[languages.en]
  languageName = 'English'
  weight = 1

[languages.ja]
  languageName = '日本語'
  weight = 2
  title = 'AIと作るノート'

[menu]
[[menu.main]]
  identifier = 'documentation'
  name = 'Documentation'
  pageRef = '/docs'
  weight = 1
[[menu.main]]
  identifier = 'blog'
  name = 'Blog'
  pageRef = '/blog'
  weight = 2
[[menu.main]]
  identifier = 'about'
  name = 'About'
  pageRef = '/about'
  weight = 3
# [[menu.main]]
#   name = 'Search'
#   weight = 4
#   [menu.main.params]
#     type = 'search'
[[menu.main]]
  name = 'GitHub'
  weight = 5
  url = 'https://github.com/skitazaki/notes-with-ai'
  [menu.main.params]
    icon = 'github'


[params]
# Display the last modification date
displayUpdatedDate = true
dateFormat = "January 2, 2006"

# Display the author name of the last modified date
displayUpdatedAuthor = false

[params.navbar]
  displayTitle = true
  displayLogo = true
  [params.navbar.logo]
    path = 'images/logo.svg'
    dark = 'images/logo-dark.svg'
    # link = '/'
    width = 32
    # height = 20
[params.footer]
  displayCopyright = true
  displayPoweredBy = false

[markup]
[markup.highlight]
  noClasses = false
